### ISSUE TITLE
how to preprocess LoFTR matches for custom data

### ISSUE THREAD

**Issue by kgg012392** [HaixinShi/fmov_pose#1]
Thanks for the amazing work!

I want to use your method on custom data. [Here](https://github.com/HaixinShi/fmov_pose?tab=readme-ov-file#data), you mentioned that your method requires LoFTR matches as input. How can I preprocess LoFTR for custom data? Which pairs of frames do I need to run LoFTR on?

Or am I missing something here that your method can run without LoFTR matches?

Thanks in advance!

**Comment by HaixinShi** [comment]
Hello, you could refer to [official implementation for LoFTR](https://github.com/zju3dv/LoFTR). You could quickly read the [code for reading matches](https://github.com/HaixinShi/fmov_pose/blob/master/models/dataset.py#L330) so you would have better understanding of the format for matches supported in this repo.

A demo match txt file:
[1032_1068_match.txt](https://github.com/user-attachments/files/17641609/1032_1068_match.txt)
You can follow the provided demo dataset provided to format your custom dataset.

Yes, our method can run without LoFTR matches by [setting flow weight to zero](https://github.com/HaixinShi/fmov_pose/blob/master/confs/ho3d_virtual.conf#L38).

**Comment by kgg012392** [comment]
Thanks for the kind reply! I'm still confused at: if I want to use LoFTR matches, which pairs of frames should I run LoFTR on? `*_*_match.txt` doesn't contain all pairs of frames.

**Comment by HaixinShi** [comment]
Hello, generating exhaustive matches for all pairs would cost time so it is not practical. In our project, we only generate matches among every 10 consecutive frames, as mentioned in Figure 10 of the paper.
```
for i in range(len(images)):
    for k in range(1, 11):
        # generate matches between frame i and frame i + k
```

**Comment by kgg012392** [comment]
To process the `*_*_match.txt`, do I need to store all matches generated by LoFTR? Or is it enough to only keep matches of the object?

**Comment by kgg012392** [comment]
I took a look at your `data.tar` example. For HO3D videos, not every frame has a processed `*_*_match.txt` file, which is different from the following script (the script below iterates through every frame `i`). Am I missing something here?

> Hello, generating exhaustive matches for all pairs would cost time so it is not practical. In our project, we only generate matches among every 10 consecutive frames, as mentioned in Figure 10 of the paper.
> 
> ```
> for i in range(len(images)):
>     for k in range(1, 11):
>         # generate matches between frame i and frame i + k
> ```

**Comment by HaixinShi** [comment]
> To process the `*_*_match.txt`, do I need to store all matches generated by LoFTR? Or is it enough to only keep matches of the object?

You could crop the object based on its mask, enlarge the image, and feed to LoFTR to get better results; but you need to ensure the match coordinates follow the original resolution/position via reversing the enlarge/crop process. You could also include the matches for the whole image and [our code](https://github.com/HaixinShi/fmov_pose/blob/master/models/dataset.py#L376-L377) will filter out background matches in preprocessing step.

> I took a look at your `data.tar` example. For HO3D videos, not every frame has a processed `*_*_match.txt` file, which is different from the following script (the script below iterates through every frame `i`). Am I missing something here?
> 
> > Hello, generating exhaustive matches for all pairs would cost time so it is not practical. In our project, we only generate matches among every 10 consecutive frames, as mentioned in Figure 10 of the paper.
> > ```
> > for i in range(len(images)):
> >     for k in range(1, 11):
> >         # generate matches between frame i and frame i + k
> > ```

This is a code showing how to generate matches by calling match predictors like LoFTR; however, you would find that for some frame pairs, LoFTR will fail in predicting reasonable matches, which can be checked by forward-backward consistency(big difference between predictions from frame pairs: i -> i + k and i + k -> i), low confidence scores, or very few predictions.

Notice that our framework doesn't fully trust the quality of matches and we use them only for regularization. So missing matches for some pairs, noisy matches, or even without matches, our system can work though it may suffer some degration.
